#pragma once
void MatterAccessControlPluginServerInitCallback();
void MatterAdministratorCommissioningPluginServerInitCallback();
void MatterBasicInformationPluginServerInitCallback();
void MatterBindingPluginServerInitCallback();
void MatterContentAppObserverPluginServerInitCallback();
void MatterDescriptorPluginServerInitCallback();
void MatterEthernetNetworkDiagnosticsPluginServerInitCallback();
void MatterGeneralCommissioningPluginServerInitCallback();
void MatterGeneralDiagnosticsPluginServerInitCallback();
void MatterGroupKeyManagementPluginServerInitCallback();
void MatterGroupsPluginServerInitCallback();
void MatterIdentifyPluginServerInitCallback();
void MatterNetworkCommissioningPluginServerInitCallback();
void MatterOperationalCredentialsPluginServerInitCallback();
void MatterSoftwareDiagnosticsPluginServerInitCallback();
void MatterUnitLocalizationPluginServerInitCallback();
void MatterWiFiNetworkDiagnosticsPluginServerInitCallback();
void MatterAccessControlPluginServerShutdownCallback();
void MatterAdministratorCommissioningPluginServerShutdownCallback();
void MatterBasicInformationPluginServerShutdownCallback();
void MatterBindingPluginServerShutdownCallback();
void MatterContentAppObserverPluginServerShutdownCallback();
void MatterDescriptorPluginServerShutdownCallback();
void MatterEthernetNetworkDiagnosticsPluginServerShutdownCallback();
void MatterGeneralCommissioningPluginServerShutdownCallback();
void MatterGeneralDiagnosticsPluginServerShutdownCallback();
void MatterGroupKeyManagementPluginServerShutdownCallback();
void MatterGroupsPluginServerShutdownCallback();
void MatterIdentifyPluginServerShutdownCallback();
void MatterNetworkCommissioningPluginServerShutdownCallback();
void MatterOperationalCredentialsPluginServerShutdownCallback();
void MatterSoftwareDiagnosticsPluginServerShutdownCallback();
void MatterUnitLocalizationPluginServerShutdownCallback();
void MatterWiFiNetworkDiagnosticsPluginServerShutdownCallback();

#define MATTER_PLUGINS_INIT                                                                                                        \
    MatterAccessControlPluginServerInitCallback();                                                                                 \
    MatterAdministratorCommissioningPluginServerInitCallback();                                                                    \
    MatterBasicInformationPluginServerInitCallback();                                                                              \
    MatterBindingPluginServerInitCallback();                                                                                       \
    MatterContentAppObserverPluginServerInitCallback();                                                                            \
    MatterDescriptorPluginServerInitCallback();                                                                                    \
    MatterEthernetNetworkDiagnosticsPluginServerInitCallback();                                                                    \
    MatterGeneralCommissioningPluginServerInitCallback();                                                                          \
    MatterGeneralDiagnosticsPluginServerInitCallback();                                                                            \
    MatterGroupKeyManagementPluginServerInitCallback();                                                                            \
    MatterGroupsPluginServerInitCallback();                                                                                        \
    MatterIdentifyPluginServerInitCallback();                                                                                      \
    MatterNetworkCommissioningPluginServerInitCallback();                                                                          \
    MatterOperationalCredentialsPluginServerInitCallback();                                                                        \
    MatterSoftwareDiagnosticsPluginServerInitCallback();                                                                           \
    MatterUnitLocalizationPluginServerInitCallback();                                                                              \
    MatterWiFiNetworkDiagnosticsPluginServerInitCallback();

#define MATTER_PLUGINS_SHUTDOWN                                                                                                    \
    MatterAccessControlPluginServerShutdownCallback();                                                                             \
    MatterAdministratorCommissioningPluginServerShutdownCallback();                                                                \
    MatterBasicInformationPluginServerShutdownCallback();                                                                          \
    MatterBindingPluginServerShutdownCallback();                                                                                   \
    MatterContentAppObserverPluginServerShutdownCallback();                                                                        \
    MatterDescriptorPluginServerShutdownCallback();                                                                                \
    MatterEthernetNetworkDiagnosticsPluginServerShutdownCallback();                                                                \
    MatterGeneralCommissioningPluginServerShutdownCallback();                                                                      \
    MatterGeneralDiagnosticsPluginServerShutdownCallback();                                                                        \
    MatterGroupKeyManagementPluginServerShutdownCallback();                                                                        \
    MatterGroupsPluginServerShutdownCallback();                                                                                    \
    MatterIdentifyPluginServerShutdownCallback();                                                                                  \
    MatterNetworkCommissioningPluginServerShutdownCallback();                                                                      \
    MatterOperationalCredentialsPluginServerShutdownCallback();                                                                    \
    MatterSoftwareDiagnosticsPluginServerShutdownCallback();                                                                       \
    MatterUnitLocalizationPluginServerShutdownCallback();                                                                          \
    MatterWiFiNetworkDiagnosticsPluginServerShutdownCallback();
