#pragma once
void MatterAccessControlPluginServerInitCallback();
void MatterActionsPluginServerInitCallback();
void MatterActivatedCarbonFilterMonitoringPluginServerInitCallback();
void MatterAdministratorCommissioningPluginServerInitCallback();
void MatterAirQualityPluginServerInitCallback();
void MatterBallastConfigurationPluginServerInitCallback();
void MatterBasicInformationPluginServerInitCallback();
void MatterBindingPluginServerInitCallback();
void MatterBridgedDeviceBasicInformationPluginServerInitCallback();
void MatterCarbonDioxideConcentrationMeasurementPluginServerInitCallback();
void MatterCarbonMonoxideConcentrationMeasurementPluginServerInitCallback();
void MatterColorControlPluginServerInitCallback();
void MatterDescriptorPluginServerInitCallback();
void MatterDiagnosticLogsPluginServerInitCallback();
void MatterDishwasherAlarmPluginServerInitCallback();
void MatterDoorLockPluginServerInitCallback();
void MatterEthernetNetworkDiagnosticsPluginServerInitCallback();
void MatterFanControlPluginServerInitCallback();
void MatterFlowMeasurementPluginServerInitCallback();
void MatterFormaldehydeConcentrationMeasurementPluginServerInitCallback();
void MatterGeneralCommissioningPluginServerInitCallback();
void MatterGeneralDiagnosticsPluginServerInitCallback();
void MatterGroupKeyManagementPluginServerInitCallback();
void MatterGroupsPluginServerInitCallback();
void MatterHepaFilterMonitoringPluginServerInitCallback();
void MatterIdentifyPluginServerInitCallback();
void MatterIlluminanceMeasurementPluginServerInitCallback();
void MatterLaundryWasherControlsPluginServerInitCallback();
void MatterLevelControlPluginServerInitCallback();
void MatterLocalizationConfigurationPluginServerInitCallback();
void MatterNetworkCommissioningPluginServerInitCallback();
void MatterNitrogenDioxideConcentrationMeasurementPluginServerInitCallback();
void MatterOccupancySensingPluginServerInitCallback();
void MatterOnOffPluginServerInitCallback();
void MatterOperationalCredentialsPluginServerInitCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();
void MatterOzoneConcentrationMeasurementPluginServerInitCallback();
void MatterPm10ConcentrationMeasurementPluginServerInitCallback();
void MatterPm1ConcentrationMeasurementPluginServerInitCallback();
void MatterPm25ConcentrationMeasurementPluginServerInitCallback();
void MatterPowerSourceConfigurationPluginServerInitCallback();
void MatterPressureMeasurementPluginServerInitCallback();
void MatterPumpConfigurationAndControlPluginServerInitCallback();
void MatterRadonConcentrationMeasurementPluginServerInitCallback();
void MatterRefrigeratorAlarmPluginServerInitCallback();
void MatterRelativeHumidityMeasurementPluginServerInitCallback();
void MatterScenesManagementPluginServerInitCallback();
void MatterSmokeCoAlarmPluginServerInitCallback();
void MatterSoftwareDiagnosticsPluginServerInitCallback();
void MatterTemperatureControlPluginServerInitCallback();
void MatterTemperatureMeasurementPluginServerInitCallback();
void MatterThermostatPluginServerInitCallback();
void MatterThermostatUserInterfaceConfigurationPluginServerInitCallback();
void MatterThreadNetworkDiagnosticsPluginServerInitCallback();
void MatterTimeFormatLocalizationPluginServerInitCallback();
void MatterTotalVolatileOrganicCompoundsConcentrationMeasurementPluginServerInitCallback();
void MatterUnitLocalizationPluginServerInitCallback();
void MatterUserLabelPluginServerInitCallback();
void MatterWiFiNetworkDiagnosticsPluginServerInitCallback();
void MatterWindowCoveringPluginServerInitCallback();
void MatterAccessControlPluginServerShutdownCallback();
void MatterActionsPluginServerShutdownCallback();
void MatterActivatedCarbonFilterMonitoringPluginServerShutdownCallback();
void MatterAdministratorCommissioningPluginServerShutdownCallback();
void MatterAirQualityPluginServerShutdownCallback();
void MatterBallastConfigurationPluginServerShutdownCallback();
void MatterBasicInformationPluginServerShutdownCallback();
void MatterBindingPluginServerShutdownCallback();
void MatterBridgedDeviceBasicInformationPluginServerShutdownCallback();
void MatterCarbonDioxideConcentrationMeasurementPluginServerShutdownCallback();
void MatterCarbonMonoxideConcentrationMeasurementPluginServerShutdownCallback();
void MatterColorControlPluginServerShutdownCallback();
void MatterDescriptorPluginServerShutdownCallback();
void MatterDiagnosticLogsPluginServerShutdownCallback();
void MatterDishwasherAlarmPluginServerShutdownCallback();
void MatterDoorLockPluginServerShutdownCallback();
void MatterEthernetNetworkDiagnosticsPluginServerShutdownCallback();
void MatterFanControlPluginServerShutdownCallback();
void MatterFlowMeasurementPluginServerShutdownCallback();
void MatterFormaldehydeConcentrationMeasurementPluginServerShutdownCallback();
void MatterGeneralCommissioningPluginServerShutdownCallback();
void MatterGeneralDiagnosticsPluginServerShutdownCallback();
void MatterGroupKeyManagementPluginServerShutdownCallback();
void MatterGroupsPluginServerShutdownCallback();
void MatterHepaFilterMonitoringPluginServerShutdownCallback();
void MatterIdentifyPluginServerShutdownCallback();
void MatterIlluminanceMeasurementPluginServerShutdownCallback();
void MatterLaundryWasherControlsPluginServerShutdownCallback();
void MatterLevelControlPluginServerShutdownCallback();
void MatterLocalizationConfigurationPluginServerShutdownCallback();
void MatterNetworkCommissioningPluginServerShutdownCallback();
void MatterNitrogenDioxideConcentrationMeasurementPluginServerShutdownCallback();
void MatterOccupancySensingPluginServerShutdownCallback();
void MatterOnOffPluginServerShutdownCallback();
void MatterOperationalCredentialsPluginServerShutdownCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerShutdownCallback();
void MatterOzoneConcentrationMeasurementPluginServerShutdownCallback();
void MatterPm10ConcentrationMeasurementPluginServerShutdownCallback();
void MatterPm1ConcentrationMeasurementPluginServerShutdownCallback();
void MatterPm25ConcentrationMeasurementPluginServerShutdownCallback();
void MatterPowerSourceConfigurationPluginServerShutdownCallback();
void MatterPressureMeasurementPluginServerShutdownCallback();
void MatterPumpConfigurationAndControlPluginServerShutdownCallback();
void MatterRadonConcentrationMeasurementPluginServerShutdownCallback();
void MatterRefrigeratorAlarmPluginServerShutdownCallback();
void MatterRelativeHumidityMeasurementPluginServerShutdownCallback();
void MatterScenesManagementPluginServerShutdownCallback();
void MatterSmokeCoAlarmPluginServerShutdownCallback();
void MatterSoftwareDiagnosticsPluginServerShutdownCallback();
void MatterTemperatureControlPluginServerShutdownCallback();
void MatterTemperatureMeasurementPluginServerShutdownCallback();
void MatterThermostatPluginServerShutdownCallback();
void MatterThermostatUserInterfaceConfigurationPluginServerShutdownCallback();
void MatterThreadNetworkDiagnosticsPluginServerShutdownCallback();
void MatterTimeFormatLocalizationPluginServerShutdownCallback();
void MatterTotalVolatileOrganicCompoundsConcentrationMeasurementPluginServerShutdownCallback();
void MatterUnitLocalizationPluginServerShutdownCallback();
void MatterUserLabelPluginServerShutdownCallback();
void MatterWiFiNetworkDiagnosticsPluginServerShutdownCallback();
void MatterWindowCoveringPluginServerShutdownCallback();

#define MATTER_PLUGINS_INIT \
    MatterAccessControlPluginServerInitCallback(); \
    MatterActionsPluginServerInitCallback(); \
    MatterActivatedCarbonFilterMonitoringPluginServerInitCallback(); \
    MatterAdministratorCommissioningPluginServerInitCallback(); \
    MatterAirQualityPluginServerInitCallback(); \
    MatterBallastConfigurationPluginServerInitCallback(); \
    MatterBasicInformationPluginServerInitCallback(); \
    MatterBindingPluginServerInitCallback(); \
    MatterBridgedDeviceBasicInformationPluginServerInitCallback(); \
    MatterCarbonDioxideConcentrationMeasurementPluginServerInitCallback(); \
    MatterCarbonMonoxideConcentrationMeasurementPluginServerInitCallback(); \
    MatterColorControlPluginServerInitCallback(); \
    MatterDescriptorPluginServerInitCallback(); \
    MatterDiagnosticLogsPluginServerInitCallback(); \
    MatterDishwasherAlarmPluginServerInitCallback(); \
    MatterDoorLockPluginServerInitCallback(); \
    MatterEthernetNetworkDiagnosticsPluginServerInitCallback(); \
    MatterFanControlPluginServerInitCallback(); \
    MatterFlowMeasurementPluginServerInitCallback(); \
    MatterFormaldehydeConcentrationMeasurementPluginServerInitCallback(); \
    MatterGeneralCommissioningPluginServerInitCallback(); \
    MatterGeneralDiagnosticsPluginServerInitCallback(); \
    MatterGroupKeyManagementPluginServerInitCallback(); \
    MatterGroupsPluginServerInitCallback(); \
    MatterHepaFilterMonitoringPluginServerInitCallback(); \
    MatterIdentifyPluginServerInitCallback(); \
    MatterIlluminanceMeasurementPluginServerInitCallback(); \
    MatterLaundryWasherControlsPluginServerInitCallback(); \
    MatterLevelControlPluginServerInitCallback(); \
    MatterLocalizationConfigurationPluginServerInitCallback(); \
    MatterNetworkCommissioningPluginServerInitCallback(); \
    MatterNitrogenDioxideConcentrationMeasurementPluginServerInitCallback(); \
    MatterOccupancySensingPluginServerInitCallback(); \
    MatterOnOffPluginServerInitCallback(); \
    MatterOperationalCredentialsPluginServerInitCallback(); \
    MatterOtaSoftwareUpdateRequestorPluginServerInitCallback(); \
    MatterOzoneConcentrationMeasurementPluginServerInitCallback(); \
    MatterPm10ConcentrationMeasurementPluginServerInitCallback(); \
    MatterPm1ConcentrationMeasurementPluginServerInitCallback(); \
    MatterPm25ConcentrationMeasurementPluginServerInitCallback(); \
    MatterPowerSourceConfigurationPluginServerInitCallback(); \
    MatterPressureMeasurementPluginServerInitCallback(); \
    MatterPumpConfigurationAndControlPluginServerInitCallback(); \
    MatterRadonConcentrationMeasurementPluginServerInitCallback(); \
    MatterRefrigeratorAlarmPluginServerInitCallback(); \
    MatterRelativeHumidityMeasurementPluginServerInitCallback(); \
    MatterScenesManagementPluginServerInitCallback(); \
    MatterSmokeCoAlarmPluginServerInitCallback(); \
    MatterSoftwareDiagnosticsPluginServerInitCallback(); \
    MatterTemperatureControlPluginServerInitCallback(); \
    MatterTemperatureMeasurementPluginServerInitCallback(); \
    MatterThermostatPluginServerInitCallback(); \
    MatterThermostatUserInterfaceConfigurationPluginServerInitCallback(); \
    MatterThreadNetworkDiagnosticsPluginServerInitCallback(); \
    MatterTimeFormatLocalizationPluginServerInitCallback(); \
    MatterTotalVolatileOrganicCompoundsConcentrationMeasurementPluginServerInitCallback(); \
    MatterUnitLocalizationPluginServerInitCallback(); \
    MatterUserLabelPluginServerInitCallback(); \
    MatterWiFiNetworkDiagnosticsPluginServerInitCallback(); \
    MatterWindowCoveringPluginServerInitCallback();

#define MATTER_PLUGINS_SHUTDOWN \
    MatterAccessControlPluginServerShutdownCallback(); \
    MatterActionsPluginServerShutdownCallback(); \
    MatterActivatedCarbonFilterMonitoringPluginServerShutdownCallback(); \
    MatterAdministratorCommissioningPluginServerShutdownCallback(); \
    MatterAirQualityPluginServerShutdownCallback(); \
    MatterBallastConfigurationPluginServerShutdownCallback(); \
    MatterBasicInformationPluginServerShutdownCallback(); \
    MatterBindingPluginServerShutdownCallback(); \
    MatterBridgedDeviceBasicInformationPluginServerShutdownCallback(); \
    MatterCarbonDioxideConcentrationMeasurementPluginServerShutdownCallback(); \
    MatterCarbonMonoxideConcentrationMeasurementPluginServerShutdownCallback(); \
    MatterColorControlPluginServerShutdownCallback(); \
    MatterDescriptorPluginServerShutdownCallback(); \
    MatterDiagnosticLogsPluginServerShutdownCallback(); \
    MatterDishwasherAlarmPluginServerShutdownCallback(); \
    MatterDoorLockPluginServerShutdownCallback(); \
    MatterEthernetNetworkDiagnosticsPluginServerShutdownCallback(); \
    MatterFanControlPluginServerShutdownCallback(); \
    MatterFlowMeasurementPluginServerShutdownCallback(); \
    MatterFormaldehydeConcentrationMeasurementPluginServerShutdownCallback(); \
    MatterGeneralCommissioningPluginServerShutdownCallback(); \
    MatterGeneralDiagnosticsPluginServerShutdownCallback(); \
    MatterGroupKeyManagementPluginServerShutdownCallback(); \
    MatterGroupsPluginServerShutdownCallback(); \
    MatterHepaFilterMonitoringPluginServerShutdownCallback(); \
    MatterIdentifyPluginServerShutdownCallback(); \
    MatterIlluminanceMeasurementPluginServerShutdownCallback(); \
    MatterLaundryWasherControlsPluginServerShutdownCallback(); \
    MatterLevelControlPluginServerShutdownCallback(); \
    MatterLocalizationConfigurationPluginServerShutdownCallback(); \
    MatterNetworkCommissioningPluginServerShutdownCallback(); \
    MatterNitrogenDioxideConcentrationMeasurementPluginServerShutdownCallback(); \
    MatterOccupancySensingPluginServerShutdownCallback(); \
    MatterOnOffPluginServerShutdownCallback(); \
    MatterOperationalCredentialsPluginServerShutdownCallback(); \
    MatterOtaSoftwareUpdateRequestorPluginServerShutdownCallback(); \
    MatterOzoneConcentrationMeasurementPluginServerShutdownCallback(); \
    MatterPm10ConcentrationMeasurementPluginServerShutdownCallback(); \
    MatterPm1ConcentrationMeasurementPluginServerShutdownCallback(); \
    MatterPm25ConcentrationMeasurementPluginServerShutdownCallback(); \
    MatterPowerSourceConfigurationPluginServerShutdownCallback(); \
    MatterPressureMeasurementPluginServerShutdownCallback(); \
    MatterPumpConfigurationAndControlPluginServerShutdownCallback(); \
    MatterRadonConcentrationMeasurementPluginServerShutdownCallback(); \
    MatterRefrigeratorAlarmPluginServerShutdownCallback(); \
    MatterRelativeHumidityMeasurementPluginServerShutdownCallback(); \
    MatterScenesManagementPluginServerShutdownCallback(); \
    MatterSmokeCoAlarmPluginServerShutdownCallback(); \
    MatterSoftwareDiagnosticsPluginServerShutdownCallback(); \
    MatterTemperatureControlPluginServerShutdownCallback(); \
    MatterTemperatureMeasurementPluginServerShutdownCallback(); \
    MatterThermostatPluginServerShutdownCallback(); \
    MatterThermostatUserInterfaceConfigurationPluginServerShutdownCallback(); \
    MatterThreadNetworkDiagnosticsPluginServerShutdownCallback(); \
    MatterTimeFormatLocalizationPluginServerShutdownCallback(); \
    MatterTotalVolatileOrganicCompoundsConcentrationMeasurementPluginServerShutdownCallback(); \
    MatterUnitLocalizationPluginServerShutdownCallback(); \
    MatterUserLabelPluginServerShutdownCallback(); \
    MatterWiFiNetworkDiagnosticsPluginServerShutdownCallback(); \
    MatterWindowCoveringPluginServerShutdownCallback();

