#pragma once
void MatterAccessControlPluginServerInitCallback();
void MatterAdministratorCommissioningPluginServerInitCallback();
void MatterBasicInformationPluginServerInitCallback();
void MatterCommodityMeteringPluginServerInitCallback();
void MatterCommodityPricePluginServerInitCallback();
void MatterCommodityTariffPluginServerInitCallback();
void MatterDescriptorPluginServerInitCallback();
void MatterElectricalGridConditionsPluginServerInitCallback();
void MatterGeneralCommissioningPluginServerInitCallback();
void MatterGeneralDiagnosticsPluginServerInitCallback();
void MatterGroupKeyManagementPluginServerInitCallback();
void MatterIdentifyPluginServerInitCallback();
void MatterLocalizationConfigurationPluginServerInitCallback();
void MatterMeterIdentificationPluginServerInitCallback();
void MatterNetworkCommissioningPluginServerInitCallback();
void MatterOperationalCredentialsPluginServerInitCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();
void MatterUnitLocalizationPluginServerInitCallback();
void MatterAccessControlPluginServerShutdownCallback();
void MatterAdministratorCommissioningPluginServerShutdownCallback();
void MatterBasicInformationPluginServerShutdownCallback();
void MatterCommodityMeteringPluginServerShutdownCallback();
void MatterCommodityPricePluginServerShutdownCallback();
void MatterCommodityTariffPluginServerShutdownCallback();
void MatterDescriptorPluginServerShutdownCallback();
void MatterElectricalGridConditionsPluginServerShutdownCallback();
void MatterGeneralCommissioningPluginServerShutdownCallback();
void MatterGeneralDiagnosticsPluginServerShutdownCallback();
void MatterGroupKeyManagementPluginServerShutdownCallback();
void MatterIdentifyPluginServerShutdownCallback();
void MatterLocalizationConfigurationPluginServerShutdownCallback();
void MatterMeterIdentificationPluginServerShutdownCallback();
void MatterNetworkCommissioningPluginServerShutdownCallback();
void MatterOperationalCredentialsPluginServerShutdownCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerShutdownCallback();
void MatterUnitLocalizationPluginServerShutdownCallback();

#define MATTER_PLUGINS_INIT                                                                                                        \
    MatterAccessControlPluginServerInitCallback();                                                                                 \
    MatterAdministratorCommissioningPluginServerInitCallback();                                                                    \
    MatterBasicInformationPluginServerInitCallback();                                                                              \
    MatterCommodityMeteringPluginServerInitCallback();                                                                             \
    MatterCommodityPricePluginServerInitCallback();                                                                                \
    MatterCommodityTariffPluginServerInitCallback();                                                                               \
    MatterDescriptorPluginServerInitCallback();                                                                                    \
    MatterElectricalGridConditionsPluginServerInitCallback();                                                                      \
    MatterGeneralCommissioningPluginServerInitCallback();                                                                          \
    MatterGeneralDiagnosticsPluginServerInitCallback();                                                                            \
    MatterGroupKeyManagementPluginServerInitCallback();                                                                            \
    MatterIdentifyPluginServerInitCallback();                                                                                      \
    MatterLocalizationConfigurationPluginServerInitCallback();                                                                     \
    MatterMeterIdentificationPluginServerInitCallback();                                                                           \
    MatterNetworkCommissioningPluginServerInitCallback();                                                                          \
    MatterOperationalCredentialsPluginServerInitCallback();                                                                        \
    MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();                                                                    \
    MatterUnitLocalizationPluginServerInitCallback();

#define MATTER_PLUGINS_SHUTDOWN                                                                                                    \
    MatterAccessControlPluginServerShutdownCallback();                                                                             \
    MatterAdministratorCommissioningPluginServerShutdownCallback();                                                                \
    MatterBasicInformationPluginServerShutdownCallback();                                                                          \
    MatterCommodityMeteringPluginServerShutdownCallback();                                                                         \
    MatterCommodityPricePluginServerShutdownCallback();                                                                            \
    MatterCommodityTariffPluginServerShutdownCallback();                                                                           \
    MatterDescriptorPluginServerShutdownCallback();                                                                                \
    MatterElectricalGridConditionsPluginServerShutdownCallback();                                                                  \
    MatterGeneralCommissioningPluginServerShutdownCallback();                                                                      \
    MatterGeneralDiagnosticsPluginServerShutdownCallback();                                                                        \
    MatterGroupKeyManagementPluginServerShutdownCallback();                                                                        \
    MatterIdentifyPluginServerShutdownCallback();                                                                                  \
    MatterLocalizationConfigurationPluginServerShutdownCallback();                                                                 \
    MatterMeterIdentificationPluginServerShutdownCallback();                                                                       \
    MatterNetworkCommissioningPluginServerShutdownCallback();                                                                      \
    MatterOperationalCredentialsPluginServerShutdownCallback();                                                                    \
    MatterOtaSoftwareUpdateRequestorPluginServerShutdownCallback();                                                                \
    MatterUnitLocalizationPluginServerShutdownCallback();
