#pragma once
void MatterAccessControlPluginServerInitCallback();
void MatterAdministratorCommissioningPluginServerInitCallback();
void MatterBasicInformationPluginServerInitCallback();
void MatterBindingPluginServerInitCallback();
void MatterCameraAvSettingsUserLevelManagementPluginServerInitCallback();
void MatterChimePluginServerInitCallback();
void MatterDescriptorPluginServerInitCallback();
void MatterDiagnosticLogsPluginServerInitCallback();
void MatterEthernetNetworkDiagnosticsPluginServerInitCallback();
void MatterFaultInjectionPluginServerInitCallback();
void MatterGeneralCommissioningPluginServerInitCallback();
void MatterGeneralDiagnosticsPluginServerInitCallback();
void MatterGroupKeyManagementPluginServerInitCallback();
void MatterGroupsPluginServerInitCallback();
void MatterIdentifyPluginServerInitCallback();
void MatterLocalizationConfigurationPluginServerInitCallback();
void MatterNetworkCommissioningPluginServerInitCallback();
void MatterOperationalCredentialsPluginServerInitCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();
void MatterPowerSourcePluginServerInitCallback();
void MatterPushAvStreamTransportPluginServerInitCallback();
void MatterSoftwareDiagnosticsPluginServerInitCallback();
void MatterThreadNetworkDiagnosticsPluginServerInitCallback();
void MatterTimeSynchronizationPluginServerInitCallback();
void MatterTlsCertificateManagementPluginServerInitCallback();
void MatterTlsClientManagementPluginServerInitCallback();
void MatterUserLabelPluginServerInitCallback();
void MatterWebRTCTransportProviderPluginServerInitCallback();
void MatterWiFiNetworkDiagnosticsPluginServerInitCallback();
void MatterZoneManagementPluginServerInitCallback();
void MatterAccessControlPluginServerShutdownCallback();
void MatterAdministratorCommissioningPluginServerShutdownCallback();
void MatterBasicInformationPluginServerShutdownCallback();
void MatterBindingPluginServerShutdownCallback();
void MatterCameraAvSettingsUserLevelManagementPluginServerShutdownCallback();
void MatterChimePluginServerShutdownCallback();
void MatterDescriptorPluginServerShutdownCallback();
void MatterDiagnosticLogsPluginServerShutdownCallback();
void MatterEthernetNetworkDiagnosticsPluginServerShutdownCallback();
void MatterFaultInjectionPluginServerShutdownCallback();
void MatterGeneralCommissioningPluginServerShutdownCallback();
void MatterGeneralDiagnosticsPluginServerShutdownCallback();
void MatterGroupKeyManagementPluginServerShutdownCallback();
void MatterGroupsPluginServerShutdownCallback();
void MatterIdentifyPluginServerShutdownCallback();
void MatterLocalizationConfigurationPluginServerShutdownCallback();
void MatterNetworkCommissioningPluginServerShutdownCallback();
void MatterOperationalCredentialsPluginServerShutdownCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerShutdownCallback();
void MatterPowerSourcePluginServerShutdownCallback();
void MatterPushAvStreamTransportPluginServerShutdownCallback();
void MatterSoftwareDiagnosticsPluginServerShutdownCallback();
void MatterThreadNetworkDiagnosticsPluginServerShutdownCallback();
void MatterTimeSynchronizationPluginServerShutdownCallback();
void MatterTlsCertificateManagementPluginServerShutdownCallback();
void MatterTlsClientManagementPluginServerShutdownCallback();
void MatterUserLabelPluginServerShutdownCallback();
void MatterWebRTCTransportProviderPluginServerShutdownCallback();
void MatterWiFiNetworkDiagnosticsPluginServerShutdownCallback();
void MatterZoneManagementPluginServerShutdownCallback();

#define MATTER_PLUGINS_INIT                                                                                                        \
    MatterAccessControlPluginServerInitCallback();                                                                                 \
    MatterAdministratorCommissioningPluginServerInitCallback();                                                                    \
    MatterBasicInformationPluginServerInitCallback();                                                                              \
    MatterBindingPluginServerInitCallback();                                                                                       \
    MatterCameraAvSettingsUserLevelManagementPluginServerInitCallback();                                                           \
    MatterChimePluginServerInitCallback();                                                                                         \
    MatterDescriptorPluginServerInitCallback();                                                                                    \
    MatterDiagnosticLogsPluginServerInitCallback();                                                                                \
    MatterEthernetNetworkDiagnosticsPluginServerInitCallback();                                                                    \
    MatterFaultInjectionPluginServerInitCallback();                                                                                \
    MatterGeneralCommissioningPluginServerInitCallback();                                                                          \
    MatterGeneralDiagnosticsPluginServerInitCallback();                                                                            \
    MatterGroupKeyManagementPluginServerInitCallback();                                                                            \
    MatterGroupsPluginServerInitCallback();                                                                                        \
    MatterIdentifyPluginServerInitCallback();                                                                                      \
    MatterLocalizationConfigurationPluginServerInitCallback();                                                                     \
    MatterNetworkCommissioningPluginServerInitCallback();                                                                          \
    MatterOperationalCredentialsPluginServerInitCallback();                                                                        \
    MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();                                                                    \
    MatterPowerSourcePluginServerInitCallback();                                                                                   \
    MatterPushAvStreamTransportPluginServerInitCallback();                                                                         \
    MatterSoftwareDiagnosticsPluginServerInitCallback();                                                                           \
    MatterThreadNetworkDiagnosticsPluginServerInitCallback();                                                                      \
    MatterTimeSynchronizationPluginServerInitCallback();                                                                           \
    MatterTlsCertificateManagementPluginServerInitCallback();                                                                      \
    MatterTlsClientManagementPluginServerInitCallback();                                                                           \
    MatterUserLabelPluginServerInitCallback();                                                                                     \
    MatterWebRTCTransportProviderPluginServerInitCallback();                                                                       \
    MatterWiFiNetworkDiagnosticsPluginServerInitCallback();                                                                        \
    MatterZoneManagementPluginServerInitCallback();

#define MATTER_PLUGINS_SHUTDOWN                                                                                                    \
    MatterAccessControlPluginServerShutdownCallback();                                                                             \
    MatterAdministratorCommissioningPluginServerShutdownCallback();                                                                \
    MatterBasicInformationPluginServerShutdownCallback();                                                                          \
    MatterBindingPluginServerShutdownCallback();                                                                                   \
    MatterCameraAvSettingsUserLevelManagementPluginServerShutdownCallback();                                                       \
    MatterChimePluginServerShutdownCallback();                                                                                     \
    MatterDescriptorPluginServerShutdownCallback();                                                                                \
    MatterDiagnosticLogsPluginServerShutdownCallback();                                                                            \
    MatterEthernetNetworkDiagnosticsPluginServerShutdownCallback();                                                                \
    MatterFaultInjectionPluginServerShutdownCallback();                                                                            \
    MatterGeneralCommissioningPluginServerShutdownCallback();                                                                      \
    MatterGeneralDiagnosticsPluginServerShutdownCallback();                                                                        \
    MatterGroupKeyManagementPluginServerShutdownCallback();                                                                        \
    MatterGroupsPluginServerShutdownCallback();                                                                                    \
    MatterIdentifyPluginServerShutdownCallback();                                                                                  \
    MatterLocalizationConfigurationPluginServerShutdownCallback();                                                                 \
    MatterNetworkCommissioningPluginServerShutdownCallback();                                                                      \
    MatterOperationalCredentialsPluginServerShutdownCallback();                                                                    \
    MatterOtaSoftwareUpdateRequestorPluginServerShutdownCallback();                                                                \
    MatterPowerSourcePluginServerShutdownCallback();                                                                               \
    MatterPushAvStreamTransportPluginServerShutdownCallback();                                                                     \
    MatterSoftwareDiagnosticsPluginServerShutdownCallback();                                                                       \
    MatterThreadNetworkDiagnosticsPluginServerShutdownCallback();                                                                  \
    MatterTimeSynchronizationPluginServerShutdownCallback();                                                                       \
    MatterTlsCertificateManagementPluginServerShutdownCallback();                                                                  \
    MatterTlsClientManagementPluginServerShutdownCallback();                                                                       \
    MatterUserLabelPluginServerShutdownCallback();                                                                                 \
    MatterWebRTCTransportProviderPluginServerShutdownCallback();                                                                   \
    MatterWiFiNetworkDiagnosticsPluginServerShutdownCallback();                                                                    \
    MatterZoneManagementPluginServerShutdownCallback();
