#pragma once
void MatterAccessControlPluginServerInitCallback();
void MatterAdministratorCommissioningPluginServerInitCallback();
void MatterBasicInformationPluginServerInitCallback();
void MatterBooleanStatePluginServerInitCallback();
void MatterDescriptorPluginServerInitCallback();
void MatterDiagnosticLogsPluginServerInitCallback();
void MatterGeneralCommissioningPluginServerInitCallback();
void MatterGeneralDiagnosticsPluginServerInitCallback();
void MatterGroupKeyManagementPluginServerInitCallback();
void MatterIcdManagementPluginServerInitCallback();
void MatterIdentifyPluginServerInitCallback();
void MatterNetworkCommissioningPluginServerInitCallback();
void MatterOperationalCredentialsPluginServerInitCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();
void MatterPowerSourcePluginServerInitCallback();
void MatterPowerSourceConfigurationPluginServerInitCallback();
void MatterSoftwareDiagnosticsPluginServerInitCallback();
void MatterThreadNetworkDiagnosticsPluginServerInitCallback();
void MatterAccessControlPluginServerShutdownCallback();
void MatterAdministratorCommissioningPluginServerShutdownCallback();
void MatterBasicInformationPluginServerShutdownCallback();
void MatterBooleanStatePluginServerShutdownCallback();
void MatterDescriptorPluginServerShutdownCallback();
void MatterDiagnosticLogsPluginServerShutdownCallback();
void MatterGeneralCommissioningPluginServerShutdownCallback();
void MatterGeneralDiagnosticsPluginServerShutdownCallback();
void MatterGroupKeyManagementPluginServerShutdownCallback();
void MatterIcdManagementPluginServerShutdownCallback();
void MatterIdentifyPluginServerShutdownCallback();
void MatterNetworkCommissioningPluginServerShutdownCallback();
void MatterOperationalCredentialsPluginServerShutdownCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerShutdownCallback();
void MatterPowerSourcePluginServerShutdownCallback();
void MatterPowerSourceConfigurationPluginServerShutdownCallback();
void MatterSoftwareDiagnosticsPluginServerShutdownCallback();
void MatterThreadNetworkDiagnosticsPluginServerShutdownCallback();

#define MATTER_PLUGINS_INIT                                                                                                        \
    MatterAccessControlPluginServerInitCallback();                                                                                 \
    MatterAdministratorCommissioningPluginServerInitCallback();                                                                    \
    MatterBasicInformationPluginServerInitCallback();                                                                              \
    MatterBooleanStatePluginServerInitCallback();                                                                                  \
    MatterDescriptorPluginServerInitCallback();                                                                                    \
    MatterDiagnosticLogsPluginServerInitCallback();                                                                                \
    MatterGeneralCommissioningPluginServerInitCallback();                                                                          \
    MatterGeneralDiagnosticsPluginServerInitCallback();                                                                            \
    MatterGroupKeyManagementPluginServerInitCallback();                                                                            \
    MatterIcdManagementPluginServerInitCallback();                                                                                 \
    MatterIdentifyPluginServerInitCallback();                                                                                      \
    MatterNetworkCommissioningPluginServerInitCallback();                                                                          \
    MatterOperationalCredentialsPluginServerInitCallback();                                                                        \
    MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();                                                                    \
    MatterPowerSourcePluginServerInitCallback();                                                                                   \
    MatterPowerSourceConfigurationPluginServerInitCallback();                                                                      \
    MatterSoftwareDiagnosticsPluginServerInitCallback();                                                                           \
    MatterThreadNetworkDiagnosticsPluginServerInitCallback();

#define MATTER_PLUGINS_SHUTDOWN                                                                                                    \
    MatterAccessControlPluginServerShutdownCallback();                                                                             \
    MatterAdministratorCommissioningPluginServerShutdownCallback();                                                                \
    MatterBasicInformationPluginServerShutdownCallback();                                                                          \
    MatterBooleanStatePluginServerShutdownCallback();                                                                              \
    MatterDescriptorPluginServerShutdownCallback();                                                                                \
    MatterDiagnosticLogsPluginServerShutdownCallback();                                                                            \
    MatterGeneralCommissioningPluginServerShutdownCallback();                                                                      \
    MatterGeneralDiagnosticsPluginServerShutdownCallback();                                                                        \
    MatterGroupKeyManagementPluginServerShutdownCallback();                                                                        \
    MatterIcdManagementPluginServerShutdownCallback();                                                                             \
    MatterIdentifyPluginServerShutdownCallback();                                                                                  \
    MatterNetworkCommissioningPluginServerShutdownCallback();                                                                      \
    MatterOperationalCredentialsPluginServerShutdownCallback();                                                                    \
    MatterOtaSoftwareUpdateRequestorPluginServerShutdownCallback();                                                                \
    MatterPowerSourcePluginServerShutdownCallback();                                                                               \
    MatterPowerSourceConfigurationPluginServerShutdownCallback();                                                                  \
    MatterSoftwareDiagnosticsPluginServerShutdownCallback();                                                                       \
    MatterThreadNetworkDiagnosticsPluginServerShutdownCallback();
