#pragma once
void MatterAccessControlPluginServerInitCallback();
void MatterAdministratorCommissioningPluginServerInitCallback();
void MatterBasicInformationPluginServerInitCallback();
void MatterDescriptorPluginServerInitCallback();
void MatterDeviceEnergyManagementPluginServerInitCallback();
void MatterDeviceEnergyManagementModePluginServerInitCallback();
void MatterElectricalEnergyMeasurementPluginServerInitCallback();
void MatterElectricalPowerMeasurementPluginServerInitCallback();
void MatterGeneralCommissioningPluginServerInitCallback();
void MatterGeneralDiagnosticsPluginServerInitCallback();
void MatterGroupKeyManagementPluginServerInitCallback();
void MatterIdentifyPluginServerInitCallback();
void MatterLocalizationConfigurationPluginServerInitCallback();
void MatterNetworkCommissioningPluginServerInitCallback();
void MatterOnOffPluginServerInitCallback();
void MatterOperationalCredentialsPluginServerInitCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();
void MatterPowerTopologyPluginServerInitCallback();
void MatterThermostatPluginServerInitCallback();
void MatterUnitLocalizationPluginServerInitCallback();
void MatterWaterHeaterManagementPluginServerInitCallback();
void MatterWaterHeaterModePluginServerInitCallback();
void MatterAccessControlPluginServerShutdownCallback();
void MatterAdministratorCommissioningPluginServerShutdownCallback();
void MatterBasicInformationPluginServerShutdownCallback();
void MatterDescriptorPluginServerShutdownCallback();
void MatterDeviceEnergyManagementPluginServerShutdownCallback();
void MatterDeviceEnergyManagementModePluginServerShutdownCallback();
void MatterElectricalEnergyMeasurementPluginServerShutdownCallback();
void MatterElectricalPowerMeasurementPluginServerShutdownCallback();
void MatterGeneralCommissioningPluginServerShutdownCallback();
void MatterGeneralDiagnosticsPluginServerShutdownCallback();
void MatterGroupKeyManagementPluginServerShutdownCallback();
void MatterIdentifyPluginServerShutdownCallback();
void MatterLocalizationConfigurationPluginServerShutdownCallback();
void MatterNetworkCommissioningPluginServerShutdownCallback();
void MatterOnOffPluginServerShutdownCallback();
void MatterOperationalCredentialsPluginServerShutdownCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerShutdownCallback();
void MatterPowerTopologyPluginServerShutdownCallback();
void MatterThermostatPluginServerShutdownCallback();
void MatterUnitLocalizationPluginServerShutdownCallback();
void MatterWaterHeaterManagementPluginServerShutdownCallback();
void MatterWaterHeaterModePluginServerShutdownCallback();

#define MATTER_PLUGINS_INIT                                                                                                        \
    MatterAccessControlPluginServerInitCallback();                                                                                 \
    MatterAdministratorCommissioningPluginServerInitCallback();                                                                    \
    MatterBasicInformationPluginServerInitCallback();                                                                              \
    MatterDescriptorPluginServerInitCallback();                                                                                    \
    MatterDeviceEnergyManagementPluginServerInitCallback();                                                                        \
    MatterDeviceEnergyManagementModePluginServerInitCallback();                                                                    \
    MatterElectricalEnergyMeasurementPluginServerInitCallback();                                                                   \
    MatterElectricalPowerMeasurementPluginServerInitCallback();                                                                    \
    MatterGeneralCommissioningPluginServerInitCallback();                                                                          \
    MatterGeneralDiagnosticsPluginServerInitCallback();                                                                            \
    MatterGroupKeyManagementPluginServerInitCallback();                                                                            \
    MatterIdentifyPluginServerInitCallback();                                                                                      \
    MatterLocalizationConfigurationPluginServerInitCallback();                                                                     \
    MatterNetworkCommissioningPluginServerInitCallback();                                                                          \
    MatterOnOffPluginServerInitCallback();                                                                                         \
    MatterOperationalCredentialsPluginServerInitCallback();                                                                        \
    MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();                                                                    \
    MatterPowerTopologyPluginServerInitCallback();                                                                                 \
    MatterThermostatPluginServerInitCallback();                                                                                    \
    MatterUnitLocalizationPluginServerInitCallback();                                                                              \
    MatterWaterHeaterManagementPluginServerInitCallback();                                                                         \
    MatterWaterHeaterModePluginServerInitCallback();

#define MATTER_PLUGINS_SHUTDOWN                                                                                                    \
    MatterAccessControlPluginServerShutdownCallback();                                                                             \
    MatterAdministratorCommissioningPluginServerShutdownCallback();                                                                \
    MatterBasicInformationPluginServerShutdownCallback();                                                                          \
    MatterDescriptorPluginServerShutdownCallback();                                                                                \
    MatterDeviceEnergyManagementPluginServerShutdownCallback();                                                                    \
    MatterDeviceEnergyManagementModePluginServerShutdownCallback();                                                                \
    MatterElectricalEnergyMeasurementPluginServerShutdownCallback();                                                               \
    MatterElectricalPowerMeasurementPluginServerShutdownCallback();                                                                \
    MatterGeneralCommissioningPluginServerShutdownCallback();                                                                      \
    MatterGeneralDiagnosticsPluginServerShutdownCallback();                                                                        \
    MatterGroupKeyManagementPluginServerShutdownCallback();                                                                        \
    MatterIdentifyPluginServerShutdownCallback();                                                                                  \
    MatterLocalizationConfigurationPluginServerShutdownCallback();                                                                 \
    MatterNetworkCommissioningPluginServerShutdownCallback();                                                                      \
    MatterOnOffPluginServerShutdownCallback();                                                                                     \
    MatterOperationalCredentialsPluginServerShutdownCallback();                                                                    \
    MatterOtaSoftwareUpdateRequestorPluginServerShutdownCallback();                                                                \
    MatterPowerTopologyPluginServerShutdownCallback();                                                                             \
    MatterThermostatPluginServerShutdownCallback();                                                                                \
    MatterUnitLocalizationPluginServerShutdownCallback();                                                                          \
    MatterWaterHeaterManagementPluginServerShutdownCallback();                                                                     \
    MatterWaterHeaterModePluginServerShutdownCallback();
