#pragma once
void MatterAccessControlPluginServerInitCallback();
void MatterAccountLoginPluginServerInitCallback();
void MatterActionsPluginServerInitCallback();
void MatterAdministratorCommissioningPluginServerInitCallback();
void MatterApplicationBasicPluginServerInitCallback();
void MatterApplicationLauncherPluginServerInitCallback();
void MatterAudioOutputPluginServerInitCallback();
void MatterBasicInformationPluginServerInitCallback();
void MatterBooleanStatePluginServerInitCallback();
void MatterBridgedDeviceBasicInformationPluginServerInitCallback();
void MatterChannelPluginServerInitCallback();
void MatterColorControlPluginServerInitCallback();
void MatterContentLauncherPluginServerInitCallback();
void MatterDescriptorPluginServerInitCallback();
void MatterDoorLockPluginServerInitCallback();
void MatterEthernetNetworkDiagnosticsPluginServerInitCallback();
void MatterFlowMeasurementPluginServerInitCallback();
void MatterGeneralCommissioningPluginServerInitCallback();
void MatterGeneralDiagnosticsPluginServerInitCallback();
void MatterGroupKeyManagementPluginServerInitCallback();
void MatterGroupsPluginServerInitCallback();
void MatterIdentifyPluginServerInitCallback();
void MatterIlluminanceMeasurementPluginServerInitCallback();
void MatterKeypadInputPluginServerInitCallback();
void MatterLevelControlPluginServerInitCallback();
void MatterMediaInputPluginServerInitCallback();
void MatterMediaPlaybackPluginServerInitCallback();
void MatterModeSelectPluginServerInitCallback();
void MatterNetworkCommissioningPluginServerInitCallback();
void MatterOccupancySensingPluginServerInitCallback();
void MatterOnOffPluginServerInitCallback();
void MatterOperationalCredentialsPluginServerInitCallback();
void MatterPowerSourcePluginServerInitCallback();
void MatterPressureMeasurementPluginServerInitCallback();
void MatterPumpConfigurationAndControlPluginServerInitCallback();
void MatterRelativeHumidityMeasurementPluginServerInitCallback();
void MatterScenesManagementPluginServerInitCallback();
void MatterSoftwareDiagnosticsPluginServerInitCallback();
void MatterSwitchPluginServerInitCallback();
void MatterTargetNavigatorPluginServerInitCallback();
void MatterTemperatureMeasurementPluginServerInitCallback();
void MatterThermostatPluginServerInitCallback();
void MatterThermostatUserInterfaceConfigurationPluginServerInitCallback();
void MatterThreadBorderRouterManagementPluginServerInitCallback();
void MatterThreadNetworkDiagnosticsPluginServerInitCallback();
void MatterUserLabelPluginServerInitCallback();
void MatterWiFiNetworkDiagnosticsPluginServerInitCallback();
void MatterWindowCoveringPluginServerInitCallback();
void MatterAccessControlPluginServerShutdownCallback();
void MatterAccountLoginPluginServerShutdownCallback();
void MatterActionsPluginServerShutdownCallback();
void MatterAdministratorCommissioningPluginServerShutdownCallback();
void MatterApplicationBasicPluginServerShutdownCallback();
void MatterApplicationLauncherPluginServerShutdownCallback();
void MatterAudioOutputPluginServerShutdownCallback();
void MatterBasicInformationPluginServerShutdownCallback();
void MatterBooleanStatePluginServerShutdownCallback();
void MatterBridgedDeviceBasicInformationPluginServerShutdownCallback();
void MatterChannelPluginServerShutdownCallback();
void MatterColorControlPluginServerShutdownCallback();
void MatterContentLauncherPluginServerShutdownCallback();
void MatterDescriptorPluginServerShutdownCallback();
void MatterDoorLockPluginServerShutdownCallback();
void MatterEthernetNetworkDiagnosticsPluginServerShutdownCallback();
void MatterFlowMeasurementPluginServerShutdownCallback();
void MatterGeneralCommissioningPluginServerShutdownCallback();
void MatterGeneralDiagnosticsPluginServerShutdownCallback();
void MatterGroupKeyManagementPluginServerShutdownCallback();
void MatterGroupsPluginServerShutdownCallback();
void MatterIdentifyPluginServerShutdownCallback();
void MatterIlluminanceMeasurementPluginServerShutdownCallback();
void MatterKeypadInputPluginServerShutdownCallback();
void MatterLevelControlPluginServerShutdownCallback();
void MatterMediaInputPluginServerShutdownCallback();
void MatterMediaPlaybackPluginServerShutdownCallback();
void MatterModeSelectPluginServerShutdownCallback();
void MatterNetworkCommissioningPluginServerShutdownCallback();
void MatterOccupancySensingPluginServerShutdownCallback();
void MatterOnOffPluginServerShutdownCallback();
void MatterOperationalCredentialsPluginServerShutdownCallback();
void MatterPowerSourcePluginServerShutdownCallback();
void MatterPressureMeasurementPluginServerShutdownCallback();
void MatterPumpConfigurationAndControlPluginServerShutdownCallback();
void MatterRelativeHumidityMeasurementPluginServerShutdownCallback();
void MatterScenesManagementPluginServerShutdownCallback();
void MatterSoftwareDiagnosticsPluginServerShutdownCallback();
void MatterSwitchPluginServerShutdownCallback();
void MatterTargetNavigatorPluginServerShutdownCallback();
void MatterTemperatureMeasurementPluginServerShutdownCallback();
void MatterThermostatPluginServerShutdownCallback();
void MatterThermostatUserInterfaceConfigurationPluginServerShutdownCallback();
void MatterThreadBorderRouterManagementPluginServerShutdownCallback();
void MatterThreadNetworkDiagnosticsPluginServerShutdownCallback();
void MatterUserLabelPluginServerShutdownCallback();
void MatterWiFiNetworkDiagnosticsPluginServerShutdownCallback();
void MatterWindowCoveringPluginServerShutdownCallback();

#define MATTER_PLUGINS_INIT \
    MatterAccessControlPluginServerInitCallback(); \
    MatterAccountLoginPluginServerInitCallback(); \
    MatterActionsPluginServerInitCallback(); \
    MatterAdministratorCommissioningPluginServerInitCallback(); \
    MatterApplicationBasicPluginServerInitCallback(); \
    MatterApplicationLauncherPluginServerInitCallback(); \
    MatterAudioOutputPluginServerInitCallback(); \
    MatterBasicInformationPluginServerInitCallback(); \
    MatterBooleanStatePluginServerInitCallback(); \
    MatterBridgedDeviceBasicInformationPluginServerInitCallback(); \
    MatterChannelPluginServerInitCallback(); \
    MatterColorControlPluginServerInitCallback(); \
    MatterContentLauncherPluginServerInitCallback(); \
    MatterDescriptorPluginServerInitCallback(); \
    MatterDoorLockPluginServerInitCallback(); \
    MatterEthernetNetworkDiagnosticsPluginServerInitCallback(); \
    MatterFlowMeasurementPluginServerInitCallback(); \
    MatterGeneralCommissioningPluginServerInitCallback(); \
    MatterGeneralDiagnosticsPluginServerInitCallback(); \
    MatterGroupKeyManagementPluginServerInitCallback(); \
    MatterGroupsPluginServerInitCallback(); \
    MatterIdentifyPluginServerInitCallback(); \
    MatterIlluminanceMeasurementPluginServerInitCallback(); \
    MatterKeypadInputPluginServerInitCallback(); \
    MatterLevelControlPluginServerInitCallback(); \
    MatterMediaInputPluginServerInitCallback(); \
    MatterMediaPlaybackPluginServerInitCallback(); \
    MatterModeSelectPluginServerInitCallback(); \
    MatterNetworkCommissioningPluginServerInitCallback(); \
    MatterOccupancySensingPluginServerInitCallback(); \
    MatterOnOffPluginServerInitCallback(); \
    MatterOperationalCredentialsPluginServerInitCallback(); \
    MatterPowerSourcePluginServerInitCallback(); \
    MatterPressureMeasurementPluginServerInitCallback(); \
    MatterPumpConfigurationAndControlPluginServerInitCallback(); \
    MatterRelativeHumidityMeasurementPluginServerInitCallback(); \
    MatterScenesManagementPluginServerInitCallback(); \
    MatterSoftwareDiagnosticsPluginServerInitCallback(); \
    MatterSwitchPluginServerInitCallback(); \
    MatterTargetNavigatorPluginServerInitCallback(); \
    MatterTemperatureMeasurementPluginServerInitCallback(); \
    MatterThermostatPluginServerInitCallback(); \
    MatterThermostatUserInterfaceConfigurationPluginServerInitCallback(); \
    MatterThreadBorderRouterManagementPluginServerInitCallback(); \
    MatterThreadNetworkDiagnosticsPluginServerInitCallback(); \
    MatterUserLabelPluginServerInitCallback(); \
    MatterWiFiNetworkDiagnosticsPluginServerInitCallback(); \
    MatterWindowCoveringPluginServerInitCallback();

#define MATTER_PLUGINS_SHUTDOWN \
    MatterAccessControlPluginServerShutdownCallback(); \
    MatterAccountLoginPluginServerShutdownCallback(); \
    MatterActionsPluginServerShutdownCallback(); \
    MatterAdministratorCommissioningPluginServerShutdownCallback(); \
    MatterApplicationBasicPluginServerShutdownCallback(); \
    MatterApplicationLauncherPluginServerShutdownCallback(); \
    MatterAudioOutputPluginServerShutdownCallback(); \
    MatterBasicInformationPluginServerShutdownCallback(); \
    MatterBooleanStatePluginServerShutdownCallback(); \
    MatterBridgedDeviceBasicInformationPluginServerShutdownCallback(); \
    MatterChannelPluginServerShutdownCallback(); \
    MatterColorControlPluginServerShutdownCallback(); \
    MatterContentLauncherPluginServerShutdownCallback(); \
    MatterDescriptorPluginServerShutdownCallback(); \
    MatterDoorLockPluginServerShutdownCallback(); \
    MatterEthernetNetworkDiagnosticsPluginServerShutdownCallback(); \
    MatterFlowMeasurementPluginServerShutdownCallback(); \
    MatterGeneralCommissioningPluginServerShutdownCallback(); \
    MatterGeneralDiagnosticsPluginServerShutdownCallback(); \
    MatterGroupKeyManagementPluginServerShutdownCallback(); \
    MatterGroupsPluginServerShutdownCallback(); \
    MatterIdentifyPluginServerShutdownCallback(); \
    MatterIlluminanceMeasurementPluginServerShutdownCallback(); \
    MatterKeypadInputPluginServerShutdownCallback(); \
    MatterLevelControlPluginServerShutdownCallback(); \
    MatterMediaInputPluginServerShutdownCallback(); \
    MatterMediaPlaybackPluginServerShutdownCallback(); \
    MatterModeSelectPluginServerShutdownCallback(); \
    MatterNetworkCommissioningPluginServerShutdownCallback(); \
    MatterOccupancySensingPluginServerShutdownCallback(); \
    MatterOnOffPluginServerShutdownCallback(); \
    MatterOperationalCredentialsPluginServerShutdownCallback(); \
    MatterPowerSourcePluginServerShutdownCallback(); \
    MatterPressureMeasurementPluginServerShutdownCallback(); \
    MatterPumpConfigurationAndControlPluginServerShutdownCallback(); \
    MatterRelativeHumidityMeasurementPluginServerShutdownCallback(); \
    MatterScenesManagementPluginServerShutdownCallback(); \
    MatterSoftwareDiagnosticsPluginServerShutdownCallback(); \
    MatterSwitchPluginServerShutdownCallback(); \
    MatterTargetNavigatorPluginServerShutdownCallback(); \
    MatterTemperatureMeasurementPluginServerShutdownCallback(); \
    MatterThermostatPluginServerShutdownCallback(); \
    MatterThermostatUserInterfaceConfigurationPluginServerShutdownCallback(); \
    MatterThreadBorderRouterManagementPluginServerShutdownCallback(); \
    MatterThreadNetworkDiagnosticsPluginServerShutdownCallback(); \
    MatterUserLabelPluginServerShutdownCallback(); \
    MatterWiFiNetworkDiagnosticsPluginServerShutdownCallback(); \
    MatterWindowCoveringPluginServerShutdownCallback();

